title: Emily's Prepress Specialist Site
description: All My Info
baseurl: "" # Leave empty if publishing to the root domain
url: "https://rosette-pattern.github.io" # Replace with your site's URL
theme: minima # Example theme
markdown: kramdown
